### ISSUE TITLE
建议转去accesser维护

### ISSUE THREAD

**Issue by louiesun** [SpaceTimee/Cealing-Host#13]
校验一下证书还是很有用的。
另外，维护ip,建议注释好是官方还是sniproxy。

另外，这里有一个利用tlsfrag实现的反dpi工具
https://github.com/maoist2009/TlsFragment

**Comment by louiesun** [comment]
> 校验一下证书还是很有用的。 另外，维护ip,建议注释好是官方还是sniproxy。
> 
> 另外，这里有一个利用tlsfrag实现的反dpi工具 (目前墙也无法处理，这东西是rfc标准里的，据说只有10%掎角旮旯里的网服务器不支持)https://github.com/maoist2009/TlsFragment

**Comment by louiesun** [comment]
tls标准里还有重协商之类的也可能可以利用

**Comment by SpaceTimee** [comment]
感谢建议，Cealing Host 欢迎所有项目使用，如果希望 Accesser 支持 Cealing Host 请向 Accesser 提交 issue 或 pr

目前除了谷歌的 ip，其他 ip 都是官方 ip

你介绍的这些技术我很感兴趣，有时间我会学习的
