### ISSUE TITLE
使用遇到的问题及一些浅浅的建议

### ISSUE THREAD

**Issue by Walker0501** [SpaceTimee/Cealing-Host#2]
主要看中了可以连接discord，然后可以顺带访问其他网站，挺不错的！

但感觉凡是涉及视频流的都加载不出来。比如discord视频消息一直转圈，然后各大视频网站比如youtube那些可以访问文字图片，但是视频就加载不出，能否解决下

然后有些列表里支持的网址貌似加载不出，看看能否优化

最后要是能再丰富下支持的网站就更好了

**Comment by SpaceTimee** [comment]
* 在 [Cealing Host 1.1.0.10](https://github.com/SpaceTimee/Cealing-Host/releases/tag/1.1.0.10) 中，现在添加了 Discord 媒体的规则，应该能解决 Discord 视频消息加载不出的问题

* Youtube 等做了大规模视频分片的网站的视频 Sheas Cealer 难以伪造，这些网站将视频的不完整"片段"分布式存储在大量不同服务器上，Sheas Cealer 只有针对每个网站写一条规则才能让视频正常播放，这可能需要成百上千条规则，所以我个人现在没有办法实现

* 内置规则会不断补充和更新常用网站的规则，但需求量和规模不大的网站不会加进内置规则，我一个人难以维护过多规则，我希望有志愿者和社区来维护特定领域的其他规则，要么就只能由用户自己添加自己需要的其他规则，Sheas Cealer 下个版本会允许用户自定义上游规则的链接，这样用户就可以自由选择不同规则了

**Comment by Walker0501** [comment]
👍👍👍

**Comment by Walker0501** [comment]
祝项目做大做强

**Comment by SpaceTimee** [comment]
谢谢
