### ISSUE TITLE
大佬可不可以添加twitch的网站规则

### ISSUE THREAD

**Issue by PAGA-Official** [SpaceTimee/Cealing-Host#3]
如题，谢谢大佬

**Comment by SpaceTimee** [comment]
Twitch 因为 assets.twitch.tv 严格校验证书导致无法伪造 (会转圈或者白屏)，在 [1.1.1.7](https://github.com/SpaceTimee/Cealing-Host/releases/tag/1.1.1.7) 被移除

**Comment by Xihihhh** [comment]
试试把 IP 改成[futuregadget-lab.com](https://futuregadget-lab.com)的？

**Comment by SpaceTimee** [comment]
> 试试把 IP 改成[futuregadget-lab.com](https://futuregadget-lab.com)的？

没有作用哦

**Comment by Xihihhh** [comment]
> 没有作用哦

奇怪，用同是 SNI 伪造的 [Accesser](https://github.com/URenko/Accesser) 就可以

**Comment by Xihihhh** [comment]
> 能发一下你使用的 ip 吗

54.230.174.72

**Comment by SpaceTimee** [comment]
> 54.230.174.72

不行，assets.twitch.tv 依然报 421 错误

我尝试的规则:
```json
[["assets.twitch.tv"],"","54.230.174.72"],
[["*twitch.tv"],"","151.101.194.167"]
``` 
和
```json
[["assets.twitch.tv"],"futuregadget-lab.com","54.230.174.72"],
[["*twitch.tv"],"","151.101.194.167"]
```

**Comment by SpaceTimee** [comment]
> 那这个工具应该没法实现了。

我尝试了 Accesser，似乎也不能访问 Twitch
https://github.com/URenko/Accesser/issues/181#issuecomment-2315122298

**Comment by SpaceTimee** [comment]
https://github.com/URenko/Accesser/issues/181#issuecomment-2315339244
难受了，理论上基于浏览器参数注入和基于代理的 SNI 伪造底层原理一模一样，可以访问的网站范围应该完全相同才对，看来这个问题还得再研究研究了

**Comment by PAGA-Official** [comment]
没事，用kick吧

**Comment by SpaceTimee** [comment]
> [URenko/Accesser#181 (comment)](https://github.com/URenko/Accesser/issues/181#issuecomment-2315339244) 难受了，理论上基于浏览器参数注入和基于代理的 SNI 伪造底层原理一模一样，可以访问的网站范围应该完全相同才对，看来这个问题还得再研究研究了

我想我应该找到原因了，基于 Chromium 参数注入实现的 SNI 伪造 只能将 Server Name 修改为一个不完全由空白字符组成的非空字符串 (如果为空白或空字符串，Chromium 无法正确读取这段启动参数)，同时也无法将 SNI 拓展标记整个删除，而像 Accesser, WattToolKit 这类基于代理的项目则不受这些条件限制，它们默认所做的也正是直接删除整个 SNI 拓展标记，这就是 Sheas Cealer 即使使用与 Accesser 完全相同的 ip 也无法直连 assets.twitch.tv 的原因，我猜测 Twitch 可能在 源服务器 或 CloudFlare 上使用了某些设置，以允许不带有 SNI 拓展标记的连接正常握手，而将 Server Name 不正确但保留了 SNI 拓展标记的连接阻断 (例如让 CloudFlare 在数据包没有 SNI 拓展标记时不验证证书，有 SNI 拓展标记时验证证书)，我暂时没有什么解决办法，好在这样的做法似乎并不十分常见

注: 结论通过使用 WireShark 抓包 Accesser 和 Sheas Cealer 伪造的数据包 然后 比较两组数据包的区别所得，两组数据包默认情况下的 tls 版本不同，我已经通过 Chromium 启动参数统一为 TLS 1.2

**Comment by SpaceTimee** [comment]
[1.1.2.4](https://github.com/SpaceTimee/Cealing-Host/releases/tag/1.1.2.4) 中已实现对 assets.twitch.tv 等网站的伪造，我上面所猜测的原因是正确的
