### ISSUE TITLE
YouTube看不了视频，一直转圈圈

### ISSUE THREAD

**Issue by PAGA-Official** [SpaceTimee/Cealing-Host#4]
![IMG_20240630_120036.jpg](https://github.com/SpaceTimee/Cealing-Host/assets/123882032/5d13d0d3-098f-48f9-a8dd-6a4d90b72f2f)

**Comment by SpaceTimee** [comment]
Youtube 视频有证书和[分片](https://github.com/SpaceTimee/Cealing-Host/issues/2#issuecomment-2150168519)问题，难以伪造

**Comment by SpaceTimee** [comment]
Youtube 视频播放问题目前已解决

**Comment by loveexception** [comment]
我还是有这个问题
如何测试

**Comment by SpaceTimee** [comment]
> 我还是有这个问题 如何测试

本地 ping 一下 [2a02:a30:6006:1e12::c] 看看能不能 ping 通，如果 ping 不通说明你的网络环境不支持访问 ipv6
