### ISSUE TITLE
请求出一篇自己寻找网站host的教程

### ISSUE THREAD

**Issue by Holocure** [SpaceTimee/Cealing-Host#6]
请问大佬可以出教程教一教怎么自己寻找补充host吗？顺便求补充一下Hanime1.me的host。
十分感谢！！

**Comment by SpaceTimee** [comment]
hanime1.me 没有被 SNI 阻断，只受域名污染，所以不会添加进内置伪造规则中，如果需要的话可以手动添加

`[["*hanime1.me"],"hanime1.me","104.26.0.18"],`

**Comment by Garfield2005** [comment]
@SpaceTimee  期待一个自己找host的教程

**Comment by YuHan-He** [comment]
@SpaceTimee 大佬有时间可以做了吗？
