### ISSUE TITLE
浏览器显示http，会被监听吗？比如说在使用校园网的情况下，能被相关机构监听到具体流量吗？

### ISSUE THREAD

**Issue by zassen128** [SpaceTimee/Cealing-Host#9]

**Comment by SpaceTimee** [comment]
不会，显示 http 不安全的原因是证书域名与伪造后的 SNI server_name 不匹配 (因为 SNI 被 Sheas Cealer 改了)

实际上由于注入了启动参数，浏览器依然会正常使用网站提供的证书来进行 tls 握手，也就是说你和服务器之间依然是完全 https 通信的，通信内容中间人不可解密，不用担心安全问题
